[phases.setup]
nixPkgs = ["php83", "php83Extensions.intl", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.pdo_mysql", "php83Extensions.opcache", "php83Extensions.sodium", "composer"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan filament:assets"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"